### ISSUE TITLE
[Question] Is this package support carousel

### ISSUE THREAD

**Issue by umaulana** [antonKalinin/react-native-image-view#1]
thanks for this package, really great works 👍 

I just wondering if this package support carousel, I mean when I press in image, the modal will pop up and when I drag the image left or right, that image will change to another image. Is that possible
?

**Comment by antonKalinin** [comment]
Hi @umaulana. Thanks!
About your question: not yet and I am afraid not in close future. There is https://github.com/ascoders/react-native-image-viewer component that works just as you described.
I am going to implement better scroll for scaled image and custom titles. And after that will think about gallery functions.

**Comment by umaulana** [comment]
@antonKalinin thanks for your response. Please keep the great work, if I have the time, I will make help to this repo 👍

**Comment by ciriac** [comment]
@antonKalinin Great package!

It would be very nice indeed if we could pass an array of images as source.

**Comment by antonKalinin** [comment]
@ciriac Hey, yes I thinking about that and hope can implement that soon.

**Comment by mfrknv** [comment]
It's really nice, will new features come?

**Comment by antonKalinin** [comment]
@mfrknv Thanks, yes, I am currently working on carousel feature: https://twitter.com/antonkaa/status/968406787090239488

**Comment by antonKalinin** [comment]
Hi!
Since version 2.0.0 `react-native-image-view` supports carousel.
Please notice that component API has changed: instead of prop `source` please use `images`.
More info in docs and [example](https://github.com/antonKalinin/react-native-image-view/blob/master/example/App.js)

Thanks!
