### ISSUE TITLE
Cannot read property 'scale' of undefined

### ISSUE THREAD

**Issue by MaximRikel** [antonKalinin/react-native-image-view#23]
When I load images after rendering I get "Cannot read property 'scale' of undefined".

**Comment by MaximRikel** [comment]
For some reason it started working.

**Comment by MaximRikel** [comment]
I tested and now I understand the bug.
I can't render ImageView with the initial image being null.
Which means that I need to create some dummy image for it to work.
This will not work:

const DEFAULT_STATE: any = {
    item: null,
    key: 0,
    isImageViewVisible: false
}

**Comment by MaximRikel** [comment]
When I replace the image in reducer the ImageView still shows me the dummy image.

render() 
  {
    return (
        <ImageView images={[this.props.item]}
                  imageIndex={0}
                  animationType='fade'
                  isVisible={this.props.isImageViewVisible}/>  
    );
  }

**Comment by MaximRikel** [comment]
The problem is that you take the 'images' from state instead of props.

**Comment by antonKalinin** [comment]
Thanks for issue, let me investigate it. The problem is that in this version there are a lot of logic happens when component receive new images. I think you right and maybe it is not necessary to store images in state, but I need some free time to test it all. Or you can send PR :)

**Comment by MaximRikel** [comment]
Sorry, don't have the time.

**Comment by vorasudh** [comment]
Any progress with this issue?

**Comment by MaximRikel** [comment]
If you want to fix it yourself, you just need to take the images in render() from props instead of state.
