### ISSUE TITLE
White as background color in modal

### ISSUE THREAD

**Issue by apacicaps** [antonKalinin/react-native-image-view#25]
Is it possible to be able to change the background color of the modal from black to white?
I'm working with png drawings that have transparent backgrounds and only black lines and therefor "disappears" in the black modal.

**Comment by antonKalinin** [comment]
Unfortunately there is no such option now, but I think it is not really big problem to add it. Will try to do it this weekend.

**Comment by apacicaps** [comment]
That sounds great - I really appreciate it!

**Comment by antonKalinin** [comment]
Done in version **2.0.9**
Close this issue. Thanks.
