### ISSUE TITLE
Unexpected token '*' on any version after 2.0.4

### ISSUE THREAD

**Issue by iesteban** [antonKalinin/react-native-image-view#26]
After upgrading to the latest version I'm getting the following error: 
![selection_042](https://user-images.githubusercontent.com/1064224/44301555-46ac3180-a319-11e8-972a-57da169a0161.png)

When I run it in debugger mode, It works perfectly. 

When I run in a release version, it just closes  right away. 

I'm using these react versions: 
"react": "^16.3.1",
"react-native": "^0.55.4",

I'm developing on Android.

**Comment by antonKalinin** [comment]
Hi and thanks for issue! Could you try version 2.0.10? Hope it could fix it :)

**Comment by iesteban** [comment]
It's fixed. Thank you so much!!!
