### ISSUE TITLE
Android backpress button to close imageView?

### ISSUE THREAD

**Issue by fuj1w4r4** [antonKalinin/react-native-image-view#28]
Hi there,

Good day. It seems press on backpress button android not closing the ImageView.
I am proposing to add this feature.

Thanks and regards,
Fuji

**Comment by fuj1w4r4** [comment]
Hi, is there any update? anyone?

**Comment by antonKalinin** [comment]
Hey @fuj1w4r4, sorry for not responding. Will try to fix today.

**Comment by antonKalinin** [comment]
Fixed in version 2.0.12

**Comment by fuj1w4r4** [comment]
@antonKalinin hey, much appreciated! this API works great!

**Comment by abdulrahman18** [comment]
I tried close button and android back button. But it's not working. How can I close image view?

**Comment by TatianaMatumoto** [comment]
I tried to close with Android back button today and is not working :(
