### ISSUE TITLE
Close button is too close to the Status Bar on iPhoneX

### ISSUE THREAD

**Issue by ZakZubair** [antonKalinin/react-native-image-view#29]

**Comment by rohit75** [comment]
Facing same issue, not able to click on some devices

**Comment by conglin890** [comment]
fixed in this

https://github.com/antonKalinin/react-native-image-view/pull/53

**Comment by GlmMak** [comment]
same issue

**Comment by zhonggithub** [comment]
same issue

**Comment by djschilling** [comment]
I have the same issue and it would be nice to get https://github.com/antonKalinin/react-native-image-view/pull/53 merged.
