### ISSUE TITLE
Add an option to provide activity indicator component when loading the image?

### ISSUE THREAD

**Issue by jack2684** [antonKalinin/react-native-image-view#3]
When the modal become visible, but the image is not shown yet, it is better to show an activity indicator.

This is an awesome library BTW :)

**Comment by antonKalinin** [comment]
Done in version 1.2.4:
https://github.com/antonKalinin/react-native-image-view/releases/tag/v1.2.4

Thanks! I am closing this issue, if you find any bugs feel free to reopen.
