### ISSUE TITLE
How to enable previous and next buttons

### ISSUE THREAD

**Issue by jeyakumarsbe** [antonKalinin/react-native-image-view#31]
Hi,

Is there any options to enable Next and Previous buttons on zoom image?

I have 4 images and i can able to view previous next and images using swipe option. But i required to place buttons for view previous and next images. 

If this options is already there please tell me how can i enable it.

Thanks,
Jayakumar

**Comment by antonKalinin** [comment]
Hi, @jeyakumarsbe, thanks for issue. There is no next or prev buttons now in this module, but I think I can extend API and add it. Hope I have enough time this weekend to do it and fix also some old bugs.

**Comment by jeyakumarsbe** [comment]
Hi antonKalinin,

Thank you for your quick reply. I eagerly waiting for this features and It's really helpful for my App.

Thanks,
Jayakumar

**Comment by antonKalinin** [comment]
@jeyakumarsbe Done in 2.1.0, please see README. Closing this one.

**Comment by jeyakumarsbe** [comment]
Also one more thing if i zooming the image then the prev and next buttons were disappeared. We wanted to show this buttons always.

**Comment by antonKalinin** [comment]
Hi @jeyakumarsbe, thanks for issue and sorry for bad testing :) Should be fixed now in 2.1.1.

**Comment by jeyakumarsbe** [comment]
Hi antonKalinin, 

Thanks for your quick reply and i will be waiting for 2.1.1 release :)

Thanks,
Jayakumar

**Comment by jeyakumarsbe** [comment]
Hi @antonKalinin, This is fixed and it's working fine. Thanks again.

**Comment by abdulrahman18** [comment]
Still I have this issue. I have the latest code only. But can't add the controls . Can you help me @jeyakumarsbe 

![Screenshot 2019-04-03 at 9 17 43 PM](https://user-images.githubusercontent.com/31540549/55493159-13bf6f80-5656-11e9-8754-eb47921b8d13.png)

**Comment by jeyakumarsbe** [comment]
@abdulrahman18, use like this controls={{ next: true, prev: true }}
