### ISSUE TITLE
Modal background opacity to be customized?

### ISSUE THREAD

**Issue by furlanrapha** [antonKalinin/react-native-image-view#33]
Hello, I was able to set the modal background color to white but I wanted to be able to set it to be opaque too. Is that possible? I was checking for opacity options but didn't find any.

**Comment by antonKalinin** [comment]
Hey @furlanrapha! Unfortunately it's not possible now. Could you please describe what you want to achieve in details?

**Comment by furlanrapha** [comment]
I wanted the modal to be fully white in the background (without opacity).

I was able to set it to be white but I can see the screen from the background when opening the Image View.

**Comment by rafaelfaria** [comment]
+1

**Comment by furlanrapha** [comment]
Closing since it's old.
