### ISSUE TITLE
Can i disable Up & Down Drag to close functional?

### ISSUE THREAD

**Issue by JegatheeshSelvam** [antonKalinin/react-native-image-view#34]
![drag_down](https://user-images.githubusercontent.com/6906775/49066516-5c4dc300-f247-11e8-934f-52457a657c88.png)
![drag_up](https://user-images.githubusercontent.com/6906775/49066517-5ce65980-f247-11e8-99c0-5902e527a30f.png)

Hey Hi,
          Please give me a solution for my above screenshot, I would like to disable the drag up or drag down to close the image view functionality. I want to close the image viewer by clicking the close button hence i dont want this drab up & down functionality. Is there any Props to disable this feature or we can change any line in the ImageView.js

**Comment by antonKalinin** [comment]
Hey @JegatheeshSelvam, there is no prop now to disable this functionality. Looks like it's not hard to implement it. Let me see, I hope I can do it this weekend.

**Comment by emmx** [comment]
Any update on this?

It's really difficult to swipe left or right (to change the image) with this up and down funcionality enabled. Dragging by starting on the image itself won't work in most of the cases, only dragging from the modal (if you're lucky and the image is not covering it completely) would work consistently.

Also being able to disable the zoom would be great. We need these two flags.

**Comment by vorasudh** [comment]
@antonKalinin  Were you able to work on this?

**Comment by antonKalinin** [comment]
Hey guys, sorry for no updates for this module :( 
If you still using it please find 3 new props `isSwipeCloseEnabled`, `isTapZoomEnabled`, `isPinchZoomEnabled` in version 2.1.3.
