### ISSUE TITLE
supportedOrientations

### ISSUE THREAD

**Issue by davidbiller** [antonKalinin/react-native-image-view#35]
PLS add supportedOrientations to Modal to support Orientation Changes.

**Comment by antonKalinin** [comment]
Hey @davidbiller, thanks for issue, good point. I will try to do it this weekend or earlier.

**Comment by srhtylmz19** [comment]
any update ? , when orientation changed to 'right' or 'left' up and down slide change the image :/

**Comment by kalyanijamunkar10** [comment]
same issue, any luck on this?
