### ISSUE TITLE
Warning: componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by enri90** [antonKalinin/react-native-image-view#54]
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: ImageView

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

help

**Comment by 2xSamurai** [comment]
Anyone working on this issue. I have also got the same problem.

**Comment by kantorv** [comment]
same here

**Comment by jeffraux** [comment]
Submitted a pull request for this issue. See PR #57. Used `componentDidUpdate` instead of `componentWillReceiveProps`

**Comment by antonKalinin** [comment]
Fixed in v2.1.6 (thanks to @jeffraux)
