### ISSUE TITLE
Image does not load

### ISSUE THREAD

**Issue by GabrielNexT** [antonKalinin/react-native-image-view#67]
Hello!
Thanks for the repository, it is amazing and will greatly help my project.

In my code I try to load some images with some links, to do that I create a vector with the objects. With the following code:
```
urls.forEach(item => {
      userPics.push({
        source: {
          uri: item
        },
      })
    })
```

However, when I open the image, the screen goes black.
I really don't know why, maybe the error is quite simple and I didn't detect it.

Ps: When I use the example codes, ie with a previously declared vector, it works perfectly.

**Comment by antonKalinin** [comment]
Hi @GabrielNexT, thanks for using the package.

First, could you please share a complete code sample via https://gist.github.com/
Second, I would recommend to try https://github.com/jobtoday/react-native-image-viewing as an improved and optimised version of this package

**Comment by GabrielNexT** [comment]
Ok, I will start using the new version.
[Gist](https://gist.github.com/GabrielNexT/50189fc39b8652dd6a73d02c67a340f3)
