### ISSUE TITLE
renderFooter can not display

### ISSUE THREAD

**Issue by MacrazdHao** [antonKalinin/react-native-image-view#69]
Im copy the demo of your docs like that: 
```
import ImageView from 'react-native-image-view';

const images = [
    {
        source: {
            uri: 'https://cdn.pixabay.com/photo/2017/08/17/10/47/paris-2650808_960_720.jpg',
        },
        title: 'Paris',
        width: 806,
        height: 720,
    },
];

<ImageView
    images={images}
    imageIndex={0}
    isVisible={this.state.isImageViewVisible}
    renderFooter={(currentImage) => (<View><Text>My footer</Text></View>)}
/>
```

the renderFooter can not display, though the component is working.

how can i fix this problem? It's that i used it in a wrong way?

**Comment by MacrazdHao** [comment]
oh i fixed it!!
we need to set a style for the renderFooter Component, then it showed up!

**Comment by antonKalinin** [comment]
Hey @MacrazdHao I glad you found solution!
I also would recommend to try [react-native-image-viewing](https://github.com/jobtoday/react-native-image-viewing), the better supported and newer version of this packages.
