### ISSUE TITLE
Default values for width and height

### ISSUE THREAD

**Issue by Hunsu** [antonKalinin/react-native-image-view#7]
In V1 we didn't need to specify a height and width of the image to show. In V2 it is specified but it doesn't work if don't specify one. I get the error:

    Error while updating property 'transform' of a view managed by: 'RTCImageView'

**Comment by antonKalinin** [comment]
You are right and I am going to fix it in next minor release. Anyway I recommend to specify width and heigh to make rendering more smooth and without delay.

**Comment by musicode** [comment]
i thick width and height is not required, i just have a url, i dont know its width and height.

if i want to know the info, i must to download the image.

if i download the image before image view, loading will never used.

**Comment by antonKalinin** [comment]
Fixed in version 2.0.2
